services:
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook --NotebookApp.token='' --NotebookApp.password=''
      - PYSPARK_SUBMIT_ARGS=--packages org.postgresql:postgresql:42.2.27,com.clickhouse:clickhouse-jdbc:0.4.6,org.mongodb.spark:mongo-spark-connector_2.12:10.1.1 pyspark-shell
    volumes:
      - ./notebook:/home/jovyan/work

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rbkkth3920
    ports:
      - "5432:5432"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   
      - "9000:9000"  
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - /home/fedor/clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=clickhouse
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=Rbkkth3920
